import { useState, useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAuth } from '../../context/AuthContext';
import { Colors } from '../../theme/colors';
import { Spacing } from '../../theme/spacing';
import { Radius } from '../../theme/radius';
import {
  mockProjects,
  mockAppraisals,
  mockDeliveryMetrics,
  mockSiteMetrics,
  getProjectById,
} from '../../data/mockProjects';
import {
  formatCurrency,
  formatPercent,
  getCurrencyForCountry,
} from '../../modules/countryModules';
import { hapticSuccess } from '../../utils/haptics';

const ROLE_COLORS: Record<string, string> = {
  cfo: '#22C55E',
  coo: '#3B82F6',
  sitelead: '#F97316',
  director: '#8B5CF6',
};

type ReportType = {
  id: string;
  title: string;
  icon: string;
  roles: string[];
  generator: (projectId: string, currency: string) => string;
};

export function ReportsDashboard() {
  const { user } = useAuth();
  const [selectedProjectId, setSelectedProjectId] = useState<string>('uk-001');
  const [generatedReport, setGeneratedReport] = useState<string | null>(null);
  const [reportType, setReportType] = useState<string>('');

  const userRole = user?.role || 'cfo';
  const roleColor = ROLE_COLORS[userRole] || '#22C55E';

  const selectedProject = useMemo(() => getProjectById(selectedProjectId), [selectedProjectId]);
  const appraisal = useMemo(() => mockAppraisals[selectedProjectId], [selectedProjectId]);
  const deliveryMetrics = useMemo(() => mockDeliveryMetrics[selectedProjectId], [selectedProjectId]);
  const siteMetrics = useMemo(() => mockSiteMetrics[selectedProjectId], [selectedProjectId]);
  const currency = useMemo(
    () => (selectedProject ? getCurrencyForCountry(selectedProject.country) : 'GBP'),
    [selectedProject]
  );

  const fmt = (amount: number) => formatCurrency(amount, currency);

  const reportTypes: ReportType[] = [
    {
      id: 'draw-request',
      title: 'Lender Draw Request',
      icon: 'cash-outline',
      roles: ['cfo'],
      generator: (projectId, curr) => {
        const project = getProjectById(projectId);
        const dm = mockDeliveryMetrics[projectId];
        if (!project || !dm) return '';
        const drawNumber = Math.floor(project.actualSpent / 5000000) + 1;
        const thisDrawAmount = Math.min(5000000, project.committedCosts - project.actualSpent);
        return `
LENDER DRAW REQUEST #${drawNumber}
================================
Project: ${project.name}
Date: ${new Date().toISOString().split('T')[0]}

DRAW SUMMARY
------------
This Draw: ${formatCurrency(thisDrawAmount, curr)}
Prior Draws: ${formatCurrency(project.actualSpent, curr)}
Total (incl. this): ${formatCurrency(project.actualSpent + thisDrawAmount, curr)}

PROJECT STATUS
--------------
Progress: ${dm.earnedValue ? ((dm.earnedValue / project.totalBudget) * 100).toFixed(1) : 0}%
CPI: ${dm.cpiCostPerformanceIndex.toFixed(2)}
EAC: ${formatCurrency(dm.estimateAtCompletion, curr)}

Generated by: BuildOS CFO Agent
        `.trim();
      },
    },
    {
      id: 'investor-update',
      title: 'Investor Update',
      icon: 'trending-up-outline',
      roles: ['cfo', 'director'],
      generator: (projectId, curr) => {
        const project = getProjectById(projectId);
        const app = mockAppraisals[projectId];
        const dm = mockDeliveryMetrics[projectId];
        if (!project || !app || !dm) return '';
        const eac = dm.estimateAtCompletion;
        const budgetVariance = project.totalBudget - eac;
        return `
INVESTOR UPDATE - ${new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}
${'='.repeat(40)}
Project: ${project.name}

KEY METRICS
-----------
IRR: ${formatPercent(app.irr)}
NPV: ${formatCurrency(app.npv, curr)}
Profit on Cost: ${formatPercent(app.profitOnCost)}
Profit on GDV: ${formatPercent(app.profitOnGdv)}

FINANCIAL POSITION
------------------
Budget: ${formatCurrency(project.totalBudget, curr)}
Committed: ${formatCurrency(project.committedCosts, curr)}
Actual Spent: ${formatCurrency(project.actualSpent, curr)}
EAC: ${formatCurrency(eac, curr)}
Variance: ${budgetVariance >= 0 ? '+' : ''}${formatCurrency(budgetVariance, curr)}

Generated by: BuildOS Agent
        `.trim();
      },
    },
    {
      id: 'cost-report',
      title: 'Cost Control Report',
      icon: 'calculator-outline',
      roles: ['cfo'],
      generator: (projectId, curr) => {
        const project = getProjectById(projectId);
        const dm = mockDeliveryMetrics[projectId];
        if (!project || !dm) return '';
        return `
COST CONTROL REPORT
${'='.repeat(40)}
Project: ${project.name}
Period: ${new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}

COST SUMMARY
------------
Budget: ${formatCurrency(project.totalBudget, curr)}
Actual Spent: ${formatCurrency(project.actualSpent, curr)}
EAC: ${formatCurrency(dm.estimateAtCompletion, curr)}

PERFORMANCE
-----------
CPI: ${dm.cpiCostPerformanceIndex.toFixed(3)}

COST CATEGORIES
---------------
${project.budgetLines.map((line) => {
  const variance = line.forecastFinal - line.currentBudget;
  return `${line.description}: ${formatCurrency(line.actualSpent, curr)} / ${formatCurrency(line.currentBudget, curr)} (${variance >= 0 ? '+' : ''}${formatCurrency(variance, curr)})`;
}).join('\n')}

Generated by: BuildOS CFO Agent
        `.trim();
      },
    },
    {
      id: 'reforecast',
      title: 'Schedule Reforecast',
      icon: 'calendar-outline',
      roles: ['coo'],
      generator: (projectId) => {
        const project = getProjectById(projectId);
        const dm = mockDeliveryMetrics[projectId];
        if (!project || !dm) return '';
        const criticalPath = project.scheduleActivities.filter((a) => a.isCriticalPath);
        return `
SCHEDULE REFORECAST
===================
Project: ${project.name}
Date: ${new Date().toISOString().split('T')[0]}

EXECUTIVE SUMMARY
-----------------
SPI: ${dm.spiSchedulePerformanceIndex.toFixed(2)}
Float: ${dm.criticalPathFloat} days

CURRENT DATES
-------------
Planned Completion: ${project.plannedEndDate}
Forecast Completion: ${project.forecastEndDate || 'TBD'}

CRITICAL PATH (Top 3)
---------------------
${criticalPath.slice(0, 3).map((a) => `- ${a.name}: ${a.percentComplete}%`).join('\n')}

Generated by: BuildOS COO Agent
        `.trim();
      },
    },
    {
      id: 'permit-package',
      title: 'Permit Status Package',
      icon: 'document-text-outline',
      roles: ['coo'],
      generator: (projectId) => {
        const project = getProjectById(projectId);
        if (!project) return '';
        const approved = project.permits.filter(
          (p) => p.status === 'approved' || p.status === 'approved-with-conditions'
        );
        const pending = project.permits.filter(
          (p) => p.status === 'under-review' || p.status === 'submitted'
        );
        return `
PERMIT STATUS PACKAGE
=====================
Project: ${project.name}
Date: ${new Date().toISOString().split('T')[0]}

SUMMARY
-------
Total Required: ${project.permits.length}
Approved: ${approved.length}
Pending: ${pending.length}
Completion: ${formatPercent(approved.length / Math.max(1, project.permits.length))}

APPROVED
--------
${approved.map((p) => `- ${p.type}: ${p.reference || 'Ref pending'}`).join('\n') || '- None'}

PENDING
-------
${pending.map((p) => `- ${p.type}`).join('\n') || '- None'}

Generated by: BuildOS COO Agent
        `.trim();
      },
    },
    {
      id: 'daily-report',
      title: 'Daily Site Report',
      icon: 'document-outline',
      roles: ['sitelead'],
      generator: (projectId) => {
        const project = getProjectById(projectId);
        const sm = mockSiteMetrics[projectId];
        if (!project || !sm) return '';
        const activities = project.scheduleActivities.filter((a) => a.status === 'in-progress');
        return `
DAILY SITE REPORT
=================
Project: ${project.name}
Date: ${new Date().toISOString().split('T')[0]}
Weather: Clear, 18°C

PROGRESS: ${sm.overallPercentComplete}% (Plan: ${sm.plannedPercentComplete}%)

ACTIVE WORK FRONTS:
${activities.slice(0, 4).map((a) => `- ${a.name}: ${a.percentComplete}%`).join('\n')}

SAFETY:
- LTIR: ${sm.ltir}
- Hours Worked: ${sm.hoursWorked.toLocaleString()}
- Near Misses (Week): ${sm.nearMissesThisPeriod}

CONSTRAINTS & RFIs:
- Open RFIs: ${sm.openRfis}
- Open Constraints: ${sm.openConstraints}

Generated by: BuildOS Site Agent
        `.trim();
      },
    },
    {
      id: 'safety-brief',
      title: 'Safety Briefing',
      icon: 'shield-checkmark-outline',
      roles: ['sitelead'],
      generator: (projectId) => {
        const project = getProjectById(projectId);
        const sm = mockSiteMetrics[projectId];
        if (!project || !sm) return '';
        const activities = project.scheduleActivities.filter((a) => a.status === 'in-progress');
        return `
SAFETY BRIEFING
===============
Project: ${project.name}
Date: ${new Date().toISOString().split('T')[0]}
Time: 07:00

TODAY'S FOCUS: Working at Height

KEY POINTS:
1. All work at height requires valid permit
2. Edge protection must be in place
3. Harness inspection required
4. Rescue plan reviewed

ACTIVE WORKS:
${activities.slice(0, 3).map((a) => `- ${a.name}`).join('\n')}

H&S PERFORMANCE:
- LTIR: ${sm.ltir.toFixed(2)} (Target: <1.0)
- Hours Worked: ${sm.hoursWorked.toLocaleString()}

Generated by: BuildOS Site Agent
        `.trim();
      },
    },
  ];

  const availableReports = reportTypes.filter((r) => r.roles.includes(userRole));

  const generateReport = (report: ReportType) => {
    const content = report.generator(selectedProjectId, currency);
    if (content) {
      setGeneratedReport(content);
      setReportType(report.title);
      hapticSuccess();
    }
  };

  if (!selectedProject) {
    return (
      <View style={styles.loading}>
        <Text style={styles.loadingText}>Loading...</Text>
      </View>
    );
  }

  return (
    <ScrollView contentContainerStyle={styles.container}>
      {/* Project Selector */}
      <View style={styles.projectSelector}>
        {mockProjects.map((project) => (
          <Pressable
            key={project.id}
            style={[
              styles.projectPill,
              selectedProjectId === project.id && [styles.projectPillActive, { borderColor: roleColor }],
            ]}
            onPress={() => setSelectedProjectId(project.id)}
          >
            <Text style={[styles.projectCountry, { color: roleColor }]}>{project.country}</Text>
            <Text
              style={[
                styles.projectName,
                selectedProjectId === project.id && styles.projectNameActive,
              ]}
              numberOfLines={1}
            >
              {project.name}
            </Text>
          </Pressable>
        ))}
      </View>

      {/* Report Types */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Available Reports</Text>
        <View style={styles.reportGrid}>
          {availableReports.map((report) => (
            <Pressable
              key={report.id}
              style={[styles.reportCard, { borderColor: roleColor + '30' }]}
              onPress={() => generateReport(report)}
            >
              <View style={[styles.reportIcon, { backgroundColor: roleColor + '15' }]}>
                <Ionicons name={report.icon as any} size={24} color={roleColor} />
              </View>
              <Text style={styles.reportTitle}>{report.title}</Text>
              <Ionicons name="chevron-forward" size={16} color={Colors.muted} />
            </Pressable>
          ))}
        </View>
      </View>

      {/* Generated Report */}
      {generatedReport && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Generated Report</Text>
          <View style={styles.generatedCard}>
            <View style={styles.generatedHeader}>
              <Text style={styles.generatedTitle}>{reportType}</Text>
              <View style={[styles.generatedBadge, { backgroundColor: roleColor + '20' }]}>
                <Text style={[styles.generatedBadgeText, { color: roleColor }]}>GENERATED</Text>
              </View>
            </View>
            <ScrollView style={styles.generatedContent} nestedScrollEnabled>
              <Text style={styles.generatedText}>{generatedReport}</Text>
            </ScrollView>
          </View>
        </View>
      )}

      {/* Recent Reports */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Report History</Text>
        <View style={styles.historyCard}>
          <Text style={styles.historyEmpty}>No recent reports</Text>
          <Text style={styles.historyHint}>Generated reports will appear here</Text>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: Spacing.sm,
    gap: Spacing.sm,
    paddingBottom: 100,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: Colors.muted,
    fontSize: 16,
  },
  projectSelector: {
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  projectPill: {
    flex: 1,
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    padding: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  projectPillActive: {
    // borderColor set dynamically
  },
  projectCountry: {
    fontSize: 10,
    fontWeight: '700',
  },
  projectName: {
    color: Colors.muted,
    fontSize: 11,
    fontWeight: '600',
  },
  projectNameActive: {
    color: Colors.text,
  },
  section: {
    gap: Spacing.xs,
  },
  sectionTitle: {
    color: Colors.muted,
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  reportGrid: {
    gap: Spacing.xs,
  },
  reportCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    padding: Spacing.md,
    borderWidth: 1,
    gap: Spacing.md,
  },
  reportIcon: {
    width: 44,
    height: 44,
    borderRadius: Radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reportTitle: {
    flex: 1,
    color: Colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  generatedCard: {
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
  },
  generatedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  generatedTitle: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  generatedBadge: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: Radius.sm,
  },
  generatedBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  generatedContent: {
    maxHeight: 300,
    padding: Spacing.sm,
  },
  generatedText: {
    color: Colors.text,
    fontSize: 11,
    fontFamily: 'monospace',
    lineHeight: 18,
  },
  historyCard: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: Radius.md,
    padding: Spacing.lg,
    alignItems: 'center',
  },
  historyEmpty: {
    color: Colors.muted,
    fontSize: 14,
  },
  historyHint: {
    color: Colors.muted,
    fontSize: 12,
    marginTop: 4,
  },
});
