/**
 * Budget PDF Export Service — generates a localized PDF report of approved
 * budget optimizations and shares it via the system share sheet.
 * Uses expo-print + expo-sharing.
 *
 * Locale-aware: pass `lang` (en/nl/de/fr/es/it). Defaults to 'en' so the
 * fallback PDF is at least readable to a tax-office reader. Strings live
 * in a static LABELS table — kept out of i18next to avoid pulling React
 * context into a Node-side PDF generator.
 */

import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import type { LineOptimization, ScenarioResult, CategoryOptimization } from './budgetOptimizerService';
import { formatMoney } from '../i18n/formatting';

export type PdfLang = 'en' | 'nl' | 'de' | 'fr' | 'es' | 'it';

interface PdfLabels {
  reportTitle: string;
  originalBudget: string;
  optimizedBudget: string;
  totalSavings: string;
  savingsPct: string;
  approvedOptimizations: string; // takes count
  code: string;
  description: string;
  category: string;
  current: string;
  proposal: string;
  savings: string;
  risk: string;
  riskLow: string;
  riskMedium: string;
  riskHigh: string;
  categoryOverview: string;
  optimizationCount: string;
  generatedBy: string;
  shareTitle: string; // dialog title
}

const LABELS: Record<PdfLang, PdfLabels> = {
  en: {
    reportTitle: 'Budget Optimization Report',
    originalBudget: 'Original budget', optimizedBudget: 'Optimized budget',
    totalSavings: 'Total savings', savingsPct: 'Savings %',
    approvedOptimizations: 'Approved Optimizations',
    code: 'Code', description: 'Description', category: 'Category',
    current: 'Current', proposal: 'Proposal', savings: 'Savings', risk: 'Risk',
    riskLow: 'Low', riskMedium: 'Medium', riskHigh: 'High',
    categoryOverview: 'Category overview',
    optimizationCount: '# Optimizations',
    generatedBy: 'Generated by',
    shareTitle: 'Budget Optimization',
  },
  nl: {
    reportTitle: 'Budget Optimalisatie Rapport',
    originalBudget: 'Origineel budget', optimizedBudget: 'Geoptimaliseerd budget',
    totalSavings: 'Totale besparing', savingsPct: 'Besparing %',
    approvedOptimizations: 'Goedgekeurde Optimalisaties',
    code: 'Code', description: 'Omschrijving', category: 'Categorie',
    current: 'Huidig', proposal: 'Voorstel', savings: 'Besparing', risk: 'Risico',
    riskLow: 'Laag', riskMedium: 'Middel', riskHigh: 'Hoog',
    categoryOverview: 'Categorie Overzicht',
    optimizationCount: '# Optimalisaties',
    generatedBy: 'Gegenereerd door',
    shareTitle: 'Budget Optimalisatie',
  },
  de: {
    reportTitle: 'Budget-Optimierungsbericht',
    originalBudget: 'Originalbudget', optimizedBudget: 'Optimiertes Budget',
    totalSavings: 'Gesamteinsparung', savingsPct: 'Einsparung %',
    approvedOptimizations: 'Genehmigte Optimierungen',
    code: 'Code', description: 'Beschreibung', category: 'Kategorie',
    current: 'Aktuell', proposal: 'Vorschlag', savings: 'Einsparung', risk: 'Risiko',
    riskLow: 'Niedrig', riskMedium: 'Mittel', riskHigh: 'Hoch',
    categoryOverview: 'Kategorieübersicht',
    optimizationCount: '# Optimierungen',
    generatedBy: 'Erstellt von',
    shareTitle: 'Budget-Optimierung',
  },
  fr: {
    reportTitle: "Rapport d'optimisation du budget",
    originalBudget: 'Budget original', optimizedBudget: 'Budget optimisé',
    totalSavings: 'Économies totales', savingsPct: 'Économies %',
    approvedOptimizations: 'Optimisations approuvées',
    code: 'Code', description: 'Description', category: 'Catégorie',
    current: 'Actuel', proposal: 'Proposition', savings: 'Économie', risk: 'Risque',
    riskLow: 'Faible', riskMedium: 'Moyen', riskHigh: 'Élevé',
    categoryOverview: 'Vue par catégorie',
    optimizationCount: '# Optimisations',
    generatedBy: 'Généré par',
    shareTitle: 'Optimisation du budget',
  },
  es: {
    reportTitle: 'Informe de optimización del presupuesto',
    originalBudget: 'Presupuesto original', optimizedBudget: 'Presupuesto optimizado',
    totalSavings: 'Ahorro total', savingsPct: 'Ahorro %',
    approvedOptimizations: 'Optimizaciones aprobadas',
    code: 'Código', description: 'Descripción', category: 'Categoría',
    current: 'Actual', proposal: 'Propuesta', savings: 'Ahorro', risk: 'Riesgo',
    riskLow: 'Bajo', riskMedium: 'Medio', riskHigh: 'Alto',
    categoryOverview: 'Vista por categoría',
    optimizationCount: '# Optimizaciones',
    generatedBy: 'Generado por',
    shareTitle: 'Optimización del presupuesto',
  },
  it: {
    reportTitle: 'Report di ottimizzazione del budget',
    originalBudget: 'Budget originale', optimizedBudget: 'Budget ottimizzato',
    totalSavings: 'Risparmio totale', savingsPct: 'Risparmio %',
    approvedOptimizations: 'Ottimizzazioni approvate',
    code: 'Codice', description: 'Descrizione', category: 'Categoria',
    current: 'Attuale', proposal: 'Proposta', savings: 'Risparmio', risk: 'Rischio',
    riskLow: 'Basso', riskMedium: 'Medio', riskHigh: 'Alto',
    categoryOverview: 'Panoramica per categoria',
    optimizationCount: '# Ottimizzazioni',
    generatedBy: 'Generato da',
    shareTitle: 'Ottimizzazione del budget',
  },
};

// ── Number formatting ──────────────────────────────────────

const fmt = (n: number) =>
  n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const fmtPct = (n: number) => `${n.toFixed(1)}%`;

const riskLabel = (risk: 'low' | 'medium' | 'high', L: PdfLabels) => {
  switch (risk) {
    case 'low': return L.riskLow;
    case 'medium': return L.riskMedium;
    case 'high': return L.riskHigh;
  }
};

const riskColor = (risk: 'low' | 'medium' | 'high') => {
  switch (risk) {
    case 'low': return '#34C759';
    case 'medium': return '#FF9500';
    case 'high': return '#FF3B30';
  }
};

// ── HTML Template ──────────────────────────────────────────

function buildHtml(
  projectName: string,
  scenario: ScenarioResult,
  approvedOptimizations: LineOptimization[],
  lang: PdfLang = 'en',
): string {
  const L = LABELS[lang] ?? LABELS.en;
  const today = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const totalApprovedSavings = approvedOptimizations.reduce((s, o) => s + o.savings, 0);

  // Category breakdown from approved optimizations
  const catMap = new Map<string, { count: number; savings: number }>();
  for (const opt of approvedOptimizations) {
    const entry = catMap.get(opt.category) ?? { count: 0, savings: 0 };
    entry.count += 1;
    entry.savings += opt.savings;
    catMap.set(opt.category, entry);
  }
  const categories = Array.from(catMap.entries())
    .sort((a, b) => b[1].savings - a[1].savings);

  const optimizationRows = approvedOptimizations
    .map(
      (opt) => `
    <tr>
      <td style="font-weight:600">${opt.costCode}</td>
      <td>${opt.description}</td>
      <td>${opt.category}</td>
      <td style="text-align:right">${formatMoney(opt.currentTotal)}</td>
      <td style="text-align:right">${formatMoney(opt.suggestedTotal)}</td>
      <td style="text-align:right;color:#34C759;font-weight:600">${formatMoney(opt.savings)}</td>
      <td style="text-align:center">
        <span style="background:${riskColor(opt.risk)}22;color:${riskColor(opt.risk)};padding:2px 8px;border-radius:4px;font-size:11px;font-weight:600">
          ${riskLabel(opt.risk, L)}
        </span>
      </td>
    </tr>`,
    )
    .join('\n');

  const categoryRows = categories
    .map(
      ([name, { count, savings }]) => `
    <tr>
      <td>${name}</td>
      <td style="text-align:center">${count}</td>
      <td style="text-align:right;color:#34C759;font-weight:600">${formatMoney(savings)}</td>
    </tr>`,
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; padding: 32px; font-size: 13px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; border-bottom: 3px solid #F97316; padding-bottom: 16px; }
    .header h1 { font-size: 22px; font-weight: 700; color: #1a1a1a; }
    .header .subtitle { font-size: 14px; color: #666; margin-top: 4px; }
    .header .date { font-size: 12px; color: #999; text-align: right; }
    .summary-grid { display: flex; gap: 16px; margin-bottom: 24px; }
    .summary-item { flex: 1; background: #f8f8f8; border-radius: 8px; padding: 16px; text-align: center; }
    .summary-item .value { font-size: 20px; font-weight: 700; color: #1a1a1a; }
    .summary-item .label { font-size: 11px; color: #666; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
    .summary-item.savings .value { color: #34C759; }
    h2 { font-size: 16px; font-weight: 700; margin: 24px 0 12px; color: #1a1a1a; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
    th { background: #f0f0f0; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; color: #666; text-align: left; padding: 8px 10px; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 12px; }
    tr:last-child td { border-bottom: none; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd; text-align: center; font-size: 11px; color: #999; }
    .accent { color: #F97316; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1>${L.reportTitle}</h1>
      <div class="subtitle">${projectName} \u2014 ${scenario.label}</div>
    </div>
    <div class="date">${today}</div>
  </div>

  <div class="summary-grid">
    <div class="summary-item">
      <div class="value">${formatMoney(scenario.totalBudget)}</div>
      <div class="label">${L.originalBudget}</div>
    </div>
    <div class="summary-item">
      <div class="value">${formatMoney(scenario.totalBudget - totalApprovedSavings)}</div>
      <div class="label">${L.optimizedBudget}</div>
    </div>
    <div class="summary-item savings">
      <div class="value">${formatMoney(totalApprovedSavings)}</div>
      <div class="label">${L.totalSavings}</div>
    </div>
    <div class="summary-item savings">
      <div class="value">${scenario.totalBudget > 0 ? fmtPct((totalApprovedSavings / scenario.totalBudget) * 100) : '0%'}</div>
      <div class="label">${L.savingsPct}</div>
    </div>
  </div>

  <h2>${L.approvedOptimizations} (${approvedOptimizations.length})</h2>
  <table>
    <thead>
      <tr>
        <th>${L.code}</th>
        <th>${L.description}</th>
        <th>${L.category}</th>
        <th style="text-align:right">${L.current}</th>
        <th style="text-align:right">${L.proposal}</th>
        <th style="text-align:right">${L.savings}</th>
        <th style="text-align:center">${L.risk}</th>
      </tr>
    </thead>
    <tbody>
      ${optimizationRows}
    </tbody>
  </table>

  <h2>${L.categoryOverview}</h2>
  <table>
    <thead>
      <tr>
        <th>${L.category}</th>
        <th style="text-align:center">${L.optimizationCount}</th>
        <th style="text-align:right">${L.totalSavings}</th>
      </tr>
    </thead>
    <tbody>
      ${categoryRows}
    </tbody>
  </table>

  <div class="footer">
    ${L.generatedBy} <span class="accent">Vasco Budget Optimizer</span> \u2014 ${today}
  </div>
</body>
</html>`;
}

// ── Export function ─────────────────────────────────────────

export async function exportBudgetPdf(
  projectName: string,
  scenario: ScenarioResult,
  approvedOptimizations: LineOptimization[],
  lang: PdfLang = 'en',
): Promise<void> {
  const html = buildHtml(projectName, scenario, approvedOptimizations, lang);
  const L = LABELS[lang] ?? LABELS.en;

  const { uri } = await Print.printToFileAsync({ html });

  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: `${L.shareTitle} — ${projectName}`,
    UTI: 'com.adobe.pdf',
  });
}
