-- =============================================================================
-- R61 / Package D — SOW (scope-of-work) generator columns
-- =============================================================================
-- Adds two columns to support AI-generated quote scope text + per-contractor
-- tone preference. The narrative SOW is generated from quote line items +
-- (later) job dossier context via the `generate-sow` edge function and
-- persisted on the documents row alongside doc_type='quote' or 'invoice'.
--
-- Per ID_COLUMN_MAP.md: documents.id stays uuid, document_number stays the
-- FE-visible string. updateDocument() dual-routes by shape (R57). No new
-- entity, no new tempId prefix — just additive columns.
--
-- Safe to run multiple times (`if not exists`).
-- =============================================================================

-- 1. Quote/invoice scope text — generated by edge fn, contractor can edit.
alter table public.documents
  add column if not exists scope_text text;

comment on column public.documents.scope_text is
  'AI-generated narrative scope of work. Includes/Excludes/Warranty paragraphs. Contractor-editable. Generated from line items + tone preset; refined from accepted-quote history once contractor has 5+ accepted quotes.';

-- 2. Per-contractor quote tone preference — cold-start replacement for
--    learned tone before the contractor has 5+ accepted quotes to learn from.
alter table public.business_settings
  add column if not exists quote_tone text default 'friendly';

-- Constrain to known values so the edge fn can route the system prompt
-- without defensive checks. Values: formal | friendly | detailed | concise.
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'business_settings'
      and constraint_name = 'business_settings_quote_tone_check'
  ) then
    alter table public.business_settings
      add constraint business_settings_quote_tone_check
      check (quote_tone is null or quote_tone in ('formal','friendly','detailed','concise'));
  end if;
end$$;

comment on column public.business_settings.quote_tone is
  'Cold-start tone preset for quote SOW generation. One of formal|friendly|detailed|concise. Once contractor accumulates 5+ accepted quotes, the SOW edge fn pulls examples from history instead of relying solely on this preset.';

-- R64 audit: business_settings was missing a unique constraint on user_id.
-- saveQuoteTonePreset uses .upsert(..., { onConflict: 'user_id' }) which
-- requires user_id to be a unique key — without it, the upsert errors at
-- write time and the contractor's tone pick silently fails to persist.
-- Add the constraint here (rather than in 004_base_schema) since this
-- migration is the first caller that depends on it. Also makes future
-- per-user-row patterns work without surprise failures.
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where table_schema = 'public'
      and table_name = 'business_settings'
      and constraint_name = 'business_settings_user_id_key'
  ) then
    alter table public.business_settings
      add constraint business_settings_user_id_key unique (user_id);
  end if;
end$$;
